title: RESTyard Documentation
description: REST made easier.
theme: just-the-docs

url: https://RESTyard.github.io/RESTyard-Docs

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

logo: "/assets/Ry-Icon_256x256.png"
favicon_ico: "/assets/Ry-Icon_48x48.png"

nav_external_links:
  - title: RESTyard on GitHub
    url: https://github.com/RESTyard/RESTyard
    hide_icon: false # set to true to hide the external link icon - defaults to false    