title: RESTyard Documentation
description: REST made easyier.
theme: just-the-docs

url: https://RESTyard.github.io/RESTyard-Docs

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red