title: RESTyard Documentation
description: REST made easyier.
theme: just-the-docs

url: https://RESTyard.github.io/RESTyard-Docs

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

logo: "/assets/Ry-Icon_256x256.png"
favicon_ico: "/assets/Ry-Icon_48x48.png"

aux_links:
  "RESTyard on GitHub":
    - "//github.com/RESTyard/RESTyard"